spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://subjectdb.c7ys8qv3ybqu.ap-southeast-2.rds.amazonaws.com:3306/hr?createDatabaseIfNotExist=true
    username: admin
    password: 12341234
  sql:
    init:
      mode: always
