spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
      javax:
        persistence:
          validation:
            mode: none
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr?createDatabaseIfNotExist=true
    username: root
    password: 1234
  sql:
    init:
      mode: always
